### ISSUE TITLE
Mettre en place une preview du site pour chaque PR

### ISSUE THREAD

**Issue by fchabouis** [etalab/transport-normes#11]
Il serait pratique d'avoir un site de preview lorsqu'on fait une PR sur le contenu d'un document.
C'est d'habitude fait automatiquement par Netlify, mais ici on a séparé le contenu du code permettant de générer le site statique, donc la fonctionnalité n'est pas présente pour une PR sur le contenu.

J'ai posé la question sur un forum Netlify https://answers.netlify.com/t/directory-chaining-and-repository-dependencies-for-pr-previews/19690, sans réponse pour le moment.

J'imagine qu'on peut faire le truc à la main, en se servant des github actions et de l'api Netlify, mais j'ai peur que ce soit un peu compliqué à mettre en place.

Sujet à creuser.

**Comment by Aurige** [comment]
on peut faire les PR directement à partir de Gitbook, et je crois qu'on peut avoit un lien vers les doc (je cours depuis 2 jours, je n'ai pas eu le temps de tester)

**Comment by fchabouis** [comment]
Tout à fait ! Cela dit, la preview peut être tout de même utile si :
* finalement l'utilisation de Gitbook n'est pas possible à cause des tableaux
* si quelqu'un (un utilisateur de la norme) fait une PR directement sur le repo sans passer par le Gitbook, par exemple pour corriger une coquille, etc

**Comment by thbar** [comment]
Je clôture:
- il y a des previews un peu manuelles pour le moment
- je vais revisiter ce sujet de toute façon (voir https://github.com/orgs/etalab/projects/35)
