### ISSUE TITLE
Discussion : mise en place d'un workflow de travail

### ISSUE THREAD

**Issue by fchabouis** [etalab/transport-normes#8]
@Aurige Je propose que nous nous servions de cette issue pour discuter des possibilités que nous trouvons pour collaborer sur les documents de normes.

Ce qui est actuellement possible :

* copier un lien depuis l'article en faisant apparaître l'ancre 
![image](https://user-images.githubusercontent.com/15341118/188426586-2712fd04-be26-49d9-875f-181c6133be03.png)
Puis ouvrir une issue et expliquer ce qui ne va pas.

ou bien

* cliquer en haut de l'article sur "proposer une modification"
![image](https://user-images.githubusercontent.com/15341118/188426788-4d225dcc-5e7c-48ee-b156-7a6d96f5f1ea.png)
Ce qui ouvre le contenu de la page.
Puis cliquer sur "display the source blob"
![image](https://user-images.githubusercontent.com/15341118/188427152-23fe02c9-581c-47e2-ba1f-aee86d623fd6.png)
trouver l'endroit qui nous intéresse avec une recherche textuelle, puis cliquer sur le numéro de la ligne, puis reference in new issue
![image](https://user-images.githubusercontent.com/15341118/188427423-f799eb5d-1c5d-4030-b166-5202afd7b29b.png)
ce qui va créer une issue avec un lien vers la passage en question.

ou bien

* ... à venir :)

**Comment by Aurige** [comment]
Merci pour ce début
C'est dommage que le basculement de **rendered** a **source** ne conserve pas la sélection et te remette en haut du document. Du coup il faut effectivement faire une recherche derrière...
Je vais creuser aussi de mon côté.

**Comment by Aurige** [comment]
Est-ce que ça vaudrait le coup de regarder du côté de GitBook ?

**Comment by fchabouis** [comment]
Oui ça peut être une bonne idée ! Je vais essayer de regarder les possibilités que cela offre. Si tu le souhaites, tu as normalement les droits pour cloner ce repo dans un Gitbook et voir si l'environnement te semble plus accessible, et on pourra en discuter.

**Comment by fchabouis** [comment]
Par curiosité, j'ai importé les documents existants dans un Gitbook.

Mes premières remarques :
- l'outil permet d'éditer directement les textes et de faire des commentaires facilement sur n'importe quel passage
- il y a une notion de "change request", avec la possibilité de review
- par contre la taille des documents, en particulier SIRI, semble rendre l'utilisation un peu laborieuse (en tout cas sur mon poste)
- l'outil ne gère pas les tableaux complexes, c'est à dire qui ne se résument pas à des lignes et des colonnes. Dès que des lignes ou des colonnes sont splitées, le tableau semble mal affiché.
Exemple d'un partie du tableau Leader :
![image](https://user-images.githubusercontent.com/15341118/188570715-8c1775de-6452-4052-bb82-7b70329b82c5.png)

**Comment by fchabouis** [comment]
En parallèle de nos tests sur Gitbook, je serai intéressé @Aurige d'essayer de faire une modification ensemble au document SIRI via une PR. Soit tu repères une coquille et tu la corrige via une PR et j'essaye de commenter dessus, soit tu me signales un problème via une issue et je fais une PR pour la corriger. Histoire de voir comment ça se comporterait sur un cas simple. N'hésite pas à revenir vers moi si tu as des questions. Et on peut aussi s'appeler et faire tout ça via un partage d'écran si tu trouves ça plus pratique !

**Comment by Aurige** [comment]
https://github.com/etalab/transport-normes/pull/9

**Comment by Aurige** [comment]
Je viens de faire un premier test de GitBook, pas de pb de perf de mon côté, c'est très fluide (mon PC a tout juste un an) ... par contre les tableaux n'ont effectivement pas aimé la conversion !

**Comment by fchabouis** [comment]
La doc de Gitbook ne semble mentionner que les tables simples :
https://docs.gitbook.com/editing-content/rich-content/with-command-palette#tables

**Comment by fchabouis** [comment]
Est-ce que tu penses que migrer le document vers des tables classiques serait envisageable ? (sans split de lignes ou de colonnes)

**Comment by Aurige** [comment]
On en discutera au prochain GT7, mais c’est envisageable 


Christophe Duquesne

**Comment by thbar** [comment]
Hello @fchabouis et merci pour ta "legacy" sur le sujet !

Ce ticket a porté ses fruits, une gouvernance publique est mise en place, voir:
- https://github.com/orgs/etalab/projects/35
- https://github.com/etalab/transport-normes/issues/35
